version: '3.7'  # версия формата файла "docker-compose.yml"

volumes:  # определяет внешние тома, которые будут использ. для хранения данных вне контейнера
  ts-db:  # имя тома, который будет создан Docker для хранения данных БД PostgreSQL

# секция, описывает список сервисов (контейнеров), которые нужно запустить
services:
  # имя сервиса, использ. внутри DockerCompose. Оно не обязательно совпадает с именем контейнера,
  # но используется для взаимодействия между контейнерами
  ts-postgres:
    container_name: notice-db-2024  # имя контейнера в Docker
    image: postgres:15.1-alpine  # какой образ Docker использовать для создания контейнера
    restart: always  # гарантирует, что контейнер будет автомат. перезапущен в случае сбоя или перезагрузки Docker
    environment:  # секция задает переменные окружения для контейнера
      POSTGRES_USER: sa  # имя пользователя для PostgreSQL
      POSTGRES_PASSWORD: admin  # пароль для пользователя 'sa'
      POSTGRES_DB: notice-db  # имя БД, которая будет создана при инициализации контейнера
    volumes:  # монтирует тома или директории с хоста в контейнер
      - ts-db:/var/lib/postgresql/data  # монтирует хостовый том 'ts-db' в директорию /var/lib/postgresql/data внутри контейнера. Это основное место, где PostgreSQL хранит данные БД
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql  # монтирует файл init-db.sql с хоста в контейнер в папку /docker-entrypoint-initdb.d/init.sql
    ports:  # открывает порты на хосте и маппирует их на порты контейнера для доступа к БД снаружи
      - "5438:5432"  # маппирует порт 5437 на хосте на порт 5432 в контейнере
        # порт 5432 — это стандартный порт для PostgreSQL
      # чтобы подключиться к БД на хосте, нужно использ. порт 5437
